### ISSUE TITLE
Add driver for iis3dwb

### ISSUE THREAD

**Issue by escherstair** [STMicroelectronics/X-CUBE-MEMS1#1]
I see a list of drivers for supported MEMS
[https://github.com/STMicroelectronics/X-CUBE-MEMS1/tree/main/Drivers/BSP/Components](https://github.com/STMicroelectronics/X-CUBE-MEMS1/tree/main/Drivers/BSP/Components)

I can't see [iis3dwb](https://github.com/STMicroelectronics/iis3dwb), which can be used with [MotionSP library](https://github.com/STMicroelectronics/X-CUBE-MEMS1/tree/main/Middlewares/ST/STM32_MotionSP_Library).

Is there any plan to integrate this driver?

**Comment by cparata** [comment]
Hi @escherstair ,
thanks for the question. I can confirm that the support to IIS3DWB will be added to the X-CUBE-MEMS1 package in the next releases.
Best Regards,
Carlo

**Comment by escherstair** [comment]
Hello @cparata can you share a roadmap for the release of the new release of X-CUBE-MEMS1 package?
It doesn't seem an actively maintained repo...

**Comment by cparata** [comment]
Hello @escherstair ,
we have published v9.2.0 last April and we are going to publish v9.3.0 in few days. X-CUBE-MEMS1 v9.3.0 will contain IIS3DWB driver and it can be used with CubeMX using X-CUBE-MEMS1 pack v9.3.0. The IIS3DWB sensor will not be used in any application contained in this package due to the high ODR frequency needed by this sensor that is not compatible with the maximum VCOM speed that we can reach on Nucleo board. Anyway, you can add the IIS3DWB driver in any custom design using CubeMX and the X-CUBE-MEMS1 pack v9.3.0.
Best Regards,
Carlo
