### ISSUE TITLE
Most recent version of MotionSP.c

### ISSUE THREAD

**Issue by escherstair** [STMicroelectronics/X-CUBE-MEMS1#6]
In this repo there is [MotionSP.c](https://github.com/STMicroelectronics/X-CUBE-MEMS1/blob/main/Middlewares/ST/STM32_MotionSP_Library/Src/MotionSP.c) which is at the moment version 2.2.0 30-May-2019
https://github.com/STMicroelectronics/X-CUBE-MEMS1/blob/0f7b5a317e866f448b583ebad1299fb93aa27794/Middlewares/ST/STM32_MotionSP_Library/Src/MotionSP.c#L5

Inside the package [FP-IND-PREDMNT1](https://www.st.com/en/embedded-software/fp-ind-predmnt1.html) version 2.4.0 I can find a different release of MotionSP.c (2.3.2 21-Oct-2020) which seems newer (from the release number), but is much smaller than this one (750 linesof code vs 1127).

Can someone clarify this?
Is it possible to have in a well know location (here?) the latest release of the ST Middleware (as an example MotionSP)?

Thanks

**Comment by cparata** [comment]
Hello @escherstair ,
the applications that you can find in the X-CUBE-MEMS1 package (VibrationMonitoring) are based on an older version of the MotionSP library v2.2.0, as you can see from the release note. The FP-IND-PREDMNT1 instead uses a new version of the MotionSP (v2.4.0). Unfortunately, the 2 library versions are not backward compatible, so in order to use the v2.4.0 in the MEMS package a rework of the application is needed. At the moment, there is no plan to update the VibrationMonitoring application of the MEMS package to support the newest version of the MotionSP library. 
Best Regards,
Carlo
