### ISSUE TITLE
Potential array overflow in iis3dwb driver

### ISSUE THREAD

**Issue by escherstair** [STMicroelectronics/X-CUBE-MEMS1#7]
@cparata the official release v9.4.0 updated the driver for iis3dwb MEMS device to the latest commit in [https://github.com/STMicroelectronics/iis3dwb-pid](https://github.com/STMicroelectronics/iis3dwb-pid)
But this introduced a potential array overflow, as described in these 2 unresolved issues (issue [#6#](https://github.com/STMicroelectronics/iis3dwb-pid/issues/6) and [#7#](https://github.com/STMicroelectronics/iis3dwb-pid/issues/7))

Is it possible to jhave a look to them (and hopefully fix them)?
Thanks

**Comment by cparata** [comment]
Hello @escherstair ,
thanks for reporting it. Anyway, the high level FIFO APIs used in this package, like "IIS3DWB_FIFO_Read", are not impacted by this issue because we do not use the buggy API "iis3dwb_fifo_out_multi_raw_get" in any high level code. So, I would close this issue. Obviously, we will update the iis3dwb-pid files as soon as the issue will be fixed in that repository.
Thanks again for the notification.
Best Regards,
Carlo
